### ISSUE TITLE
Bahia Blanca's Seaport logo has changed

### ISSUE THREAD

**Issue by martinrios95** [Juaanma/BB-Seaport-App#1]
Hi Juanma! I'm Martin, do you remember me?

Mariano received an e-mail from BB Seaport telling about their logo and colors had changed.
So, they expect that the design and wireframe (colors, logos and drawables) will change in a further version of this app.

I put this issue to create a new commit on this repo to update the app.
So, some files on the Android application will be changed in BB Seaport.

Best regards,

Martin

PS: The new logo is available on Facebook [here](https://www.facebook.com/cgpbb/).

**Comment by juanmsuarez** [comment]
Hi Martín!

Sounds great! I'll add you as a collaborator of the project.

Best wishes,
Juan.
